---
title: "_SummarizedExperiment_ for Coordinating Experimental Assays, Samples, and Regions of Interest"
author: "Martin Morgan"
date: "Revised: 18 August, 2015"
output:
  BiocStyle::html_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{SummarizedExperiment}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r style, echo=FALSE, results='asis'}
BiocStyle::markdown()
```

# Motivating use case

# Parts of a _SummarizedExperiment_

redo fig. 2 of http://www.nature.com/nmeth/journal/v12/n2/abs/nmeth.3252.html

- Visual presentation of parts of SE
- pseudo-code illustrating manipulation

## Assays

## 'Row' (regions-of-interest) data

### Genomic ranges or data frames?

## 'Column' (sample) data

## Experiment-wide metadata

# Putting it together

Often, SummarizedExperiment objects are returned by functions written
by other packages. It is possilbe to create a SummarizedExperiment 'by
hand'.

# Common operations on _SummarizedExperiment_

Subsetting

- Two-dimensional `[`
- `se$<colData column>` for easy sample selection

Getters and setters

- `rowRanges()` / (`mcols()`), `colData()`, `metadata()`
- `assay()` versus `assays()`

Range-based operations

- e.g., `subsetByOverlaps(se, roi)`

# Case study revisited -- _SummarizedExperiment_ in action

# Advanced: Extending _SummarizedExperiment_